# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 993e52eb8325643af9dbe9625d90fabe663c0d3ebf30aff2d50a859e5beace608db4f54319c5191c05304dbee34fe9464be40c848e75a4526a4c71ea35ef9ed5

test:
  secret_key_base: 559d1f3710a59ab7fee87f52ee714396f36c5bb9830a1596399fdc4bd171970d2fbe39bdeef74751d2fd1a633ee908664353c0d0dd2a2600c516bc8acc093e1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
